# /// script
# requires-python = ">=3.10"
# dependencies = [
#     "SPx @ git+https://github.com/mineralogy-rocks/SPx.git",
#     "pandas==3.0.1",
#     "matplotlib",
#     "openpyxl",
#     "marimo",
# ]
# ///

import marimo

__generated_with = "0.20.4"
app = marimo.App()


@app.cell
def _():
    import marimo as mo

    return (mo,)


@app.cell
def _(mo):
    import subprocess as _subprocess
    import sys as _sys

    try:
        import src as _src_check
    except ImportError:
        with mo.status.spinner("Installing SPx..."):
            _subprocess.check_call([
                _sys.executable, "-m", "pip", "install",
                "SPx @ git+https://github.com/mineralogy-rocks/SPx.git",
            ])
        import importlib as _importlib
        _importlib.invalidate_caches()
    return ()


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    # SPx — Spectral Unmixing

    **SPx** is a tool for processing spectral data (including but not limited to Near-Infrared (NIR)),
    extracting features, generating visualizations and statistics, and applying linear spectral unmixing
    (LSUMx) to retrieve smectite content from measured NIR spectra.

    The prediction and unmixing code was created based on
    [Gread et al. (2025)](https://doi.org/10.1016/j.clay.2025.107748).

    This notebook runs the **unmixing** stage: apply linear spectral unmixing using reference
    endmembers to find optimal mixture coefficients via bounded minimization (SciPy).

    [![Open in Marimo](https://marimo.io/shield.svg)](https://marimo.io/p/@mineralogy-rocks/spx-unmixing)

    ---

    ### Prerequisites

    - A `results.xlsx` file in the output directory (generated by the
      [processing notebook](./processing.py))
    - An `endmembers.xlsx` file with exactly **2 rows** of endmember data

    ### Endmembers Format

    The endmembers file must have:
    - First column: endmember name/ID
    - Remaining columns: spectral parameters (e.g. `D`, `2D`, `3D`, `TAr/TFWH`, `Total Slope`)
    - Exactly 2 rows of endmember data

    Need the default file? Download the
    [default endmembers from GitHub](https://github.com/mineralogy-rocks/SPx/blob/main/data/endmembers.xlsx).

    ### Prediction Requirements

    1. A valid endmembers file (first column is sample ID)
    2. Samples added to the second sheet of `results.xlsx` (first column is sample ID)
    3. The number and order of parameters must match between both files

    The output will be saved as `results_predicted.xlsx`.
    """)
    return


@app.cell
def _():
    import logging
    import os
    import tempfile

    from src.base.predict import run_prediction
    from src.config import settings

    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    return logging, os, run_prediction, settings, tempfile


@app.cell
def _(os, settings, tempfile):
    _tmpdir = tempfile.mkdtemp(prefix="spx_unmix_")
    INPUT_DIR = os.path.join(_tmpdir, "input")
    OUTPUT_DIR = os.path.join(_tmpdir, "output")
    DATA_DIR = os.path.join(OUTPUT_DIR, "data")

    os.makedirs(INPUT_DIR, exist_ok=True)
    os.makedirs(DATA_DIR, exist_ok=True)
    os.makedirs(os.path.join(OUTPUT_DIR, "plots"), exist_ok=True)

    _original_validate = settings._validate
    settings._validate = lambda: None
    settings.configure(_tmpdir, "input", "output")
    settings._validate = _original_validate
    return DATA_DIR, INPUT_DIR, OUTPUT_DIR


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Upload Results

    Upload the `results.xlsx` file generated by the processing notebook.
    """)
    return


@app.cell
def _(mo):
    results_upload = mo.ui.file(filetypes=[".xlsx"], multiple=False, kind="area", label="results.xlsx")
    results_upload
    return (results_upload,)


@app.cell
def _(DATA_DIR, mo, os, results_upload):
    if results_upload.value:
        _f = results_upload.value[0]
        _dest = os.path.join(DATA_DIR, "results.xlsx")
        with open(_dest, "wb") as _fh:
            _fh.write(_f.contents)
        mo.output.replace(mo.md("Uploaded **results.xlsx**."))
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Upload Endmembers

    Upload your `endmembers.xlsx` file.
    """)
    return


@app.cell
def _(mo):
    endmembers_upload = mo.ui.file(filetypes=[".xlsx"], multiple=False, kind="area", label="endmembers.xlsx")
    endmembers_upload
    return (endmembers_upload,)


@app.cell
def _(INPUT_DIR, endmembers_upload, mo, os):
    endmembers_path = None
    if endmembers_upload.value:
        _f = endmembers_upload.value[0]
        endmembers_path = os.path.join(INPUT_DIR, _f.name)
        with open(endmembers_path, "wb") as _fh:
            _fh.write(_f.contents)
        mo.output.replace(mo.md(f"Uploaded **{_f.name}**."))
    return (endmembers_path,)


@app.cell
def _(mo):
    run_button = mo.ui.run_button(label="Run Spectral Unmixing")
    run_button
    return (run_button,)


@app.cell
def _(endmembers_path, mo, run_button, run_prediction, settings):
    import io as _io
    import logging as _logging

    mo.stop(not run_button.value, mo.md("Click **Run Spectral Unmixing** above to start."))
    mo.stop(endmembers_path is None, mo.md("Please upload an **endmembers.xlsx** file first."))

    _log_buf = _io.StringIO()
    _handler = _logging.StreamHandler(_log_buf)
    _handler.setLevel(_logging.INFO)
    _handler.setFormatter(_logging.Formatter("%(asctime)s %(levelname)s %(message)s"))

    _root = _logging.getLogger()
    _root.addHandler(_handler)

    try:
        with mo.status.spinner("Running spectral unmixing..."):
            run_prediction(endmembers_path=endmembers_path)
    finally:
        _root.removeHandler(_handler)

    prediction_done = True
    output_path = settings.OUTPUT_PATH
    prediction_log = _log_buf.getvalue()
    return output_path, prediction_done, prediction_log


@app.cell
def _(mo, prediction_done, prediction_log):
    mo.stop(not prediction_done)
    mo.accordion({"Unmixing Log": mo.md(f"```\n{prediction_log}\n```")})
    return


@app.cell
def _(mo, output_path, prediction_done):
    import zipfile as _zipfile
    from io import BytesIO as _BytesIO
    from pathlib import Path as _Path

    import pandas as _pd

    mo.stop(not prediction_done)

    _predicted_path = output_path / "data" / "results_predicted.xlsx"
    _data_dir = output_path / "data"

    _elements = []

    # Zip output folder
    _zip_buf = _BytesIO()
    with _zipfile.ZipFile(_zip_buf, "w", _zipfile.ZIP_DEFLATED) as _zf:
        for _f in sorted(_Path(output_path).rglob("*")):
            if _f.is_file():
                _zf.write(_f, _f.relative_to(output_path))
    _zip_buf.seek(0)
    _elements.append(mo.download(data=_zip_buf.getvalue(), filename="spx_unmixing_results.zip", label="Download all results (.zip)"))

    # Results table
    if _predicted_path.exists():
        _df = _pd.read_excel(_predicted_path)
        _elements.append(mo.md("### Prediction Results"))
        _elements.append(mo.ui.table(_df))

    # Files table with individual downloads
    _all_files = []
    if _data_dir.exists():
        for _f in sorted(_data_dir.iterdir()):
            if _f.is_file():
                _all_files.append({
                    "file": _f.name,
                    "size": f"{_f.stat().st_size / 1024:.1f} KB",
                    "download": mo.download(data=_f.read_bytes(), filename=_f.name, label="Download"),
                })

    if _all_files:
        _elements.append(mo.md("### All Output Files"))
        _elements.append(mo.ui.table(_all_files, selection=None))

    mo.vstack(_elements)
    return


if __name__ == "__main__":
    app.run()
